spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://192.168.199.206:3306/sell?characterEncoding=utf-8&useSSL=false
    password: 123456
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  file: H:\WorkSpace\Web\sell\src\main\resources\logs